import { Recommendation, WatchlistItem, FriendItem } from "./supabase";

export const MOCK_RECOMMENDATIONS: Recommendation[] = [
  {
    id: "rec_1",
    sender_name: "Alex",
    sender_avatar: "aurora",
    recipient: "You",
    tmdb_id: 693134,
    media_type: "movie",
    title: "Dune: Part Two",
    poster_path: "/1pdfLPoLStWDYRGlA2L85t0Gj22.jpg",
    backdrop_path: "/xOMo8WhK21rmA2sXCVgV2D29DZa.jpg",
    release_year: "2024",
    genre: "Sci-Fi / Epic",
    rating_stars: 5.0,
    note: "Tony, you loved Blade Runner 2049, you will be blown away by the IMAX sound and scale of this!",
    tags: ["Mindbender", "MustWatchTogether"],
    created_at: "2024-03-01",
  },
  {
    id: "rec_2",
    sender_name: "Maya",
    sender_avatar: "nebula",
    recipient: "All Friends",
    tmdb_id: 95396,
    media_type: "tv",
    title: "Severance",
    poster_path: "/2c4iJvEknv2V2l7yXl1bB45wA3y.jpg",
    backdrop_path: "/xOMo8WhK21rmA2sXCVgV2D29DZa.jpg",
    release_year: "2022",
    genre: "TV Series • Thriller",
    rating_stars: 4.5,
    note: "Wild workplace mindbender. Episode 9 finale will make your jaw drop.",
    tags: ["DarkAndTwisted", "Mindbender"],
    created_at: "2024-02-28",
  },
  {
    id: "rec_3",
    sender_name: "Sam",
    sender_avatar: "ember",
    recipient: "All Friends",
    tmdb_id: 666243,
    media_type: "movie",
    title: "Palm Springs",
    poster_path: "/aIm3Kw783zLfyvMv2vW1V9l0S.jpg",
    backdrop_path: "/aIm3Kw783zLfyvMv2vW1V9l0S.jpg",
    release_year: "2020",
    genre: "Rom-Com / Sci-Fi",
    rating_stars: 4.5,
    note: "Time loop rom-com done right! Andy Samberg is hilarious in this.",
    tags: ["ComfortWatch", "Hilarious"],
    created_at: "2024-02-25",
  },
  {
    id: "rec_4",
    sender_name: "Alex",
    sender_avatar: "aurora",
    recipient: "All Friends",
    tmdb_id: 872585,
    media_type: "movie",
    title: "Oppenheimer",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/rLb2cwFXYJYazFPQjjhlUtAn6in.jpg",
    release_year: "2023",
    genre: "Biography / Drama",
    rating_stars: 5.0,
    note: "Unbelievable pacing for a 3-hour dialogue thriller. Christopher Nolan at his peak.",
    tags: ["CinematicMasterpiece"],
    created_at: "2024-02-20",
  },
  {
    id: "rec_5",
    sender_name: "Sam",
    sender_avatar: "ember",
    recipient: "Maya",
    tmdb_id: 1072790,
    media_type: "movie",
    title: "Anyone But You",
    poster_path: "/5qHoazZiaLe7oFBok7XlUhg96f2.jpg",
    backdrop_path: "/jXJxMcVoRiScIRQIhkELV0zo6Bk.jpg",
    release_year: "2023",
    genre: "Rom-Com",
    rating_stars: 4.0,
    note: "Super fun weekend romance watch. Sydney Sweeney and Glen Powell chemistry is 10/10.",
    tags: ["ComfortWatch", "FridayNightVibe"],
    created_at: "2024-02-18",
  },
  {
    id: "rec_6",
    sender_name: "Maya",
    sender_avatar: "nebula",
    recipient: "You",
    tmdb_id: 136315,
    media_type: "tv",
    title: "The Bear",
    poster_path: "/2vY1o7gE21kR8N88e1xV0u.jpg",
    backdrop_path: "/m32890589.jpg",
    release_year: "2022",
    genre: "TV Series • Drama",
    rating_stars: 5.0,
    note: "Tony! Episode 7 'Fishes' is the most intense television hour of the decade. Watch immediately!",
    tags: ["CinematicMasterpiece", "MustWatchTogether"],
    created_at: "2024-02-15",
  },
];

export const MOCK_WATCHLIST: WatchlistItem[] = [
  {
    id: "watch_1",
    tmdb_id: 693134,
    media_type: "movie",
    title: "Dune: Part Two",
    poster_path: "/1pdfLPoLStWDYRGlA2L85t0Gj22.jpg",
    release_year: "2024",
    genre: "Sci-Fi / Epic",
    status: "WANT_TO_WATCH",
    recommended_by: "Alex",
    added_at: "2024-03-01",
  },
  {
    id: "watch_2",
    tmdb_id: 95396,
    media_type: "tv",
    title: "Severance",
    poster_path: "/2c4iJvEknv2V2l7yXl1bB45wA3y.jpg",
    release_year: "2022",
    genre: "TV Series • Thriller",
    status: "WANT_TO_WATCH",
    recommended_by: "Maya",
    added_at: "2024-02-28",
  },
  {
    id: "watch_3",
    tmdb_id: 872585,
    media_type: "movie",
    title: "Oppenheimer",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_year: "2023",
    genre: "Biography / Drama",
    status: "WATCHED",
    rating_stars: 5.0,
    recommended_by: "Sam",
    added_at: "2024-01-15",
  },
];

export const MOCK_FRIENDS: FriendItem[] = [
  {
    id: "alex_1",
    username: "alex_films",
    display_name: "Alex",
    avatar_character_id: "aurora",
    status: "ACCEPTED",
    stats: { recommendedCount: 14, watchedCount: 48, topGenre: "Sci-Fi" },
  },
  {
    id: "maya_2",
    username: "maya_cine",
    display_name: "Maya",
    avatar_character_id: "nebula",
    status: "ACCEPTED",
    stats: { recommendedCount: 9, watchedCount: 36, topGenre: "Thriller" },
  },
  {
    id: "sam_3",
    username: "sam_popcorn",
    display_name: "Sam",
    avatar_character_id: "ember",
    status: "ACCEPTED",
    stats: { recommendedCount: 18, watchedCount: 62, topGenre: "Comedy" },
  },
];

export const MOCK_DEMO_PROFILE = {
  displayName: "Tony Stark",
  username: "ironman",
  avatarId: "solaris",
  age: "24",
};

export const MOCK_DEMO_EMAIL = "tony.stark@avengers.io";
